/**
 * Property-based + table-driven tests for `src/lib/permissions.ts`.
 *
 * Validates: Requirements 2.1, 2.6, 2.7, 4.5, 11.5, 15.1
 *
 * Spec references:
 *   - SPEC.md §2.1 — RBAC matrix (ADMIN full access; EMPLOYEE read all,
 *     write own, no delete, no AI cost/usage).
 *   - SPEC.md §16.1 — Unit tests (Vitest), ≥80 % line coverage on `lib/`.
 *   - design.md §"Correctness Properties" — Property 7 (admin monotonicity).
 *
 * The test plan is intentionally pure: no DB, no network, no mocks. All
 * inputs are generated by `fast-check` arbitraries that mirror the
 * canonical `Action` × `Resource` × `Role` × ownership space.
 */

import { describe, expect, it } from 'vitest';
import * as fc from 'fast-check';

import {
  ACTIONS,
  ALL_EMPLOYEE_MODULES,
  PermissionError,
  RESOURCES,
  RESOURCE_ACTIONS,
  assertCan,
  can,
  canAccessModule,
  type Action,
  type ModuleId,
  type OwnedRecord,
  type Resource,
} from './permissions';

// ---------------------------------------------------------------------------
// Test data + arbitraries
// ---------------------------------------------------------------------------

/** Resources for which an employee may write a record they own/created. */
const OWNABLE_RESOURCES = ['lead', 'campaign', 'socialPost', 'devTask'] as const;
type OwnableResource = (typeof OWNABLE_RESOURCES)[number];

/** Resources where employee writes are categorically denied (admin-only). */
const ADMIN_ONLY_WRITE_RESOURCES = ['aiInsight', 'setting'] as const;

/** Stable, distinct user IDs used across ownership tests. */
const USER_A = 'user-aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const USER_B = 'user-bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';

const adminSession = { userId: USER_A, role: 'ADMIN' as const };
const employeeSession = { userId: USER_A, role: 'EMPLOYEE' as const };

const actionArb = fc.constantFrom(...ACTIONS) as fc.Arbitrary<Action>;
const resourceArb = fc.constantFrom(...RESOURCES) as fc.Arbitrary<Resource>;

const userIdArb = fc
  .uuid()
  .map((u) => `user-${u}`); // mirror real session shape (string IDs)

/** Arbitrary record: any combination of owner/creator (or both null). */
const recordArb: fc.Arbitrary<OwnedRecord> = fc.record(
  {
    ownerId: fc.oneof(fc.constant(null), userIdArb),
    createdById: fc.oneof(fc.constant(null), userIdArb),
  },
  { requiredKeys: [] },
);

/** Arbitrary record OR `undefined` — exercises the "create-new" branch too. */
const recordOrUndefinedArb: fc.Arbitrary<OwnedRecord | undefined> = fc.option(
  recordArb,
  { nil: undefined, freq: 4 },
);

const ownableResourceArb = fc.constantFrom(
  ...OWNABLE_RESOURCES,
) as fc.Arbitrary<OwnableResource>;

// ---------------------------------------------------------------------------
// Property 7 — Admin monotonicity (SPEC.md §16.1, design Property 7)
// ---------------------------------------------------------------------------

describe('Property 7 — admin monotonicity', () => {
  it('can(admin, action, resource, record) === true for every input', () => {
    fc.assert(
      fc.property(actionArb, resourceArb, recordOrUndefinedArb, (action, resource, record) => {
        expect(can(adminSession, action, resource, record)).toBe(true);
      }),
      { numRuns: 500 },
    );
  });

  it('admin session with arbitrary userId still passes everything', () => {
    fc.assert(
      fc.property(
        userIdArb,
        actionArb,
        resourceArb,
        recordOrUndefinedArb,
        (userId, action, resource, record) => {
          expect(can({ userId, role: 'ADMIN' }, action, resource, record)).toBe(true);
        },
      ),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Employee — universal read / deny rules
// ---------------------------------------------------------------------------

describe('Employee — read is always allowed', () => {
  it("can(employee, 'read', resource) === true for every resource", () => {
    fc.assert(
      fc.property(resourceArb, recordOrUndefinedArb, (resource, record) => {
        expect(can(employeeSession, 'read', resource, record)).toBe(true);
      }),
      { numRuns: 200 },
    );
  });
});

describe('Employee — delete is always denied', () => {
  it("can(employee, 'delete', resource) === false for every resource", () => {
    fc.assert(
      fc.property(resourceArb, recordOrUndefinedArb, (resource, record) => {
        expect(can(employeeSession, 'delete', resource, record)).toBe(false);
      }),
      { numRuns: 200 },
    );
  });
});

describe('Employee — admin action is always denied', () => {
  it("can(employee, 'admin', resource) === false for every resource", () => {
    fc.assert(
      fc.property(resourceArb, recordOrUndefinedArb, (resource, record) => {
        expect(can(employeeSession, 'admin', resource, record)).toBe(false);
      }),
      { numRuns: 200 },
    );
  });
});

// ---------------------------------------------------------------------------
// Employee — write rules (ownership)
// ---------------------------------------------------------------------------

describe('Employee — owner/creator can write owned resources', () => {
  it('write returns true when record.ownerId === userId on lead/campaign/socialPost/devTask', () => {
    fc.assert(
      fc.property(
        userIdArb,
        ownableResourceArb,
        // createdById can be anything (null, same, or different)
        fc.oneof(fc.constant<string | null>(null), userIdArb),
        (userId, resource, createdById) => {
          const session = { userId, role: 'EMPLOYEE' as const };
          const record: OwnedRecord = { ownerId: userId, createdById };
          expect(can(session, 'write', resource, record)).toBe(true);
        },
      ),
      { numRuns: 200 },
    );
  });

  it('write returns true when record.createdById === userId (and ownerId differs)', () => {
    fc.assert(
      fc.property(userIdArb, userIdArb, ownableResourceArb, (userId, otherId, resource) => {
        fc.pre(userId !== otherId);
        const session = { userId, role: 'EMPLOYEE' as const };
        const record: OwnedRecord = { ownerId: otherId, createdById: userId };
        expect(can(session, 'write', resource, record)).toBe(true);
      }),
      { numRuns: 200 },
    );
  });
});

describe('Employee — non-owner / non-creator write is denied', () => {
  it('write returns false when ownerId !== userId AND createdById !== userId', () => {
    fc.assert(
      fc.property(
        userIdArb,
        userIdArb,
        userIdArb,
        resourceArb,
        (userId, otherId1, otherId2, resource) => {
          fc.pre(userId !== otherId1 && userId !== otherId2);
          const session = { userId, role: 'EMPLOYEE' as const };
          const record: OwnedRecord = { ownerId: otherId1, createdById: otherId2 };
          expect(can(session, 'write', resource, record)).toBe(false);
        },
      ),
      { numRuns: 300 },
    );
  });

  it('write returns false when both ownerId and createdById are null/missing', () => {
    fc.assert(
      fc.property(userIdArb, ownableResourceArb, (userId, resource) => {
        const session = { userId, role: 'EMPLOYEE' as const };
        // Both nulled → not "create-new" (record present), not owned → deny.
        expect(can(session, 'write', resource, { ownerId: null, createdById: null })).toBe(false);
      }),
      { numRuns: 100 },
    );
  });
});

describe('Employee — create-new (no record) on ownable resources', () => {
  it("can(employee, 'write', resource) === true when record is omitted", () => {
    fc.assert(
      fc.property(userIdArb, ownableResourceArb, (userId, resource) => {
        const session = { userId, role: 'EMPLOYEE' as const };
        expect(can(session, 'write', resource)).toBe(true);
        expect(can(session, 'write', resource, undefined)).toBe(true);
      }),
      { numRuns: 100 },
    );
  });
});

describe('Employee — admin-only write resources', () => {
  it.each(ADMIN_ONLY_WRITE_RESOURCES)(
    "can(employee, 'write', '%s') === false regardless of record",
    (resource) => {
      fc.assert(
        fc.property(recordOrUndefinedArb, (record) => {
          expect(can(employeeSession, 'write', resource, record)).toBe(false);
        }),
        { numRuns: 100 },
      );
    },
  );
});

describe("Employee — write 'user' is self-edit only", () => {
  it("write 'user' returns true iff record.ownerId === session.userId", () => {
    fc.assert(
      fc.property(userIdArb, userIdArb, (selfId, otherId) => {
        const session = { userId: selfId, role: 'EMPLOYEE' as const };
        // Self-edit
        expect(can(session, 'write', 'user', { ownerId: selfId })).toBe(true);
        // Someone else's profile
        if (selfId !== otherId) {
          expect(can(session, 'write', 'user', { ownerId: otherId })).toBe(false);
        }
        // No record at all → cannot create users
        expect(can(session, 'write', 'user')).toBe(false);
        // createdById match alone is NOT enough for the user resource
        expect(
          can(session, 'write', 'user', { ownerId: otherId, createdById: selfId }),
        ).toBe(selfId === otherId);
      }),
      { numRuns: 100 },
    );
  });
});

// ---------------------------------------------------------------------------
// Unauthenticated sessions
// ---------------------------------------------------------------------------

describe('Unauthenticated — every check is denied', () => {
  it.each<[string, null | undefined]>([
    ['null', null],
    ['undefined', undefined],
  ])('session=%s denies every (action, resource, record)', (_label, session) => {
    fc.assert(
      fc.property(actionArb, resourceArb, recordOrUndefinedArb, (action, resource, record) => {
        expect(can(session, action, resource, record)).toBe(false);
      }),
      { numRuns: 200 },
    );
  });

  it('session with missing userId is treated as unauthenticated', () => {
    fc.assert(
      fc.property(actionArb, resourceArb, (action, resource) => {
        // @ts-expect-error — exercising defensive guard for malformed sessions
        expect(can({ role: 'ADMIN' }, action, resource)).toBe(false);
        // @ts-expect-error — same: missing role
        expect(can({ userId: USER_A }, action, resource)).toBe(false);
      }),
      { numRuns: 50 },
    );
  });
});

// ---------------------------------------------------------------------------
// Table-driven tests for the explicit SPEC §2.1 RBAC matrix
// ---------------------------------------------------------------------------

describe('SPEC §2.1 — RBAC matrix (table-driven)', () => {
  // Shape: [label, session, action, resource, record?, expected]
  type Row = [
    string,
    Parameters<typeof can>[0],
    Action,
    Resource,
    OwnedRecord | undefined,
    boolean,
  ];

  const rows: Row[] = [
    // ADMIN — full access
    ['admin reads users', adminSession, 'read', 'user', undefined, true],
    ['admin writes users', adminSession, 'write', 'user', undefined, true],
    ['admin deletes users', adminSession, 'delete', 'user', undefined, true],
    ['admin views AI usage', adminSession, 'admin', 'aiInsight', undefined, true],
    ['admin writes settings', adminSession, 'write', 'setting', undefined, true],
    ['admin generates AI insight', adminSession, 'write', 'aiInsight', undefined, true],

    // EMPLOYEE — read all modules
    ['employee reads users', employeeSession, 'read', 'user', undefined, true],
    ['employee reads leads', employeeSession, 'read', 'lead', undefined, true],
    ['employee reads campaigns', employeeSession, 'read', 'campaign', undefined, true],
    ['employee reads social posts', employeeSession, 'read', 'socialPost', undefined, true],
    ['employee reads dev tasks', employeeSession, 'read', 'devTask', undefined, true],
    ['employee reads ai insights', employeeSession, 'read', 'aiInsight', undefined, true],
    ['employee reads settings', employeeSession, 'read', 'setting', undefined, true],

    // EMPLOYEE — cannot manage users (no create, no admin)
    ['employee cannot create user', employeeSession, 'write', 'user', undefined, false],
    [
      "employee cannot edit other user's profile",
      employeeSession,
      'write',
      'user',
      { ownerId: USER_B },
      false,
    ],
    [
      'employee can edit own user profile',
      employeeSession,
      'write',
      'user',
      { ownerId: USER_A },
      true,
    ],
    [
      'employee cannot delete a user',
      employeeSession,
      'delete',
      'user',
      { ownerId: USER_A },
      false,
    ],

    // EMPLOYEE — cannot view AI cost/usage (admin action on aiInsight)
    [
      'employee cannot view AI usage (admin action)',
      employeeSession,
      'admin',
      'aiInsight',
      undefined,
      false,
    ],
    [
      'employee cannot generate AI insights (write)',
      employeeSession,
      'write',
      'aiInsight',
      undefined,
      false,
    ],
    [
      'employee cannot edit settings',
      employeeSession,
      'write',
      'setting',
      undefined,
      false,
    ],

    // EMPLOYEE — write own records
    [
      'employee writes own lead',
      employeeSession,
      'write',
      'lead',
      { ownerId: USER_A },
      true,
    ],
    [
      'employee writes lead they created',
      employeeSession,
      'write',
      'lead',
      { ownerId: USER_B, createdById: USER_A },
      true,
    ],
    [
      "employee cannot write someone else's lead",
      employeeSession,
      'write',
      'lead',
      { ownerId: USER_B, createdById: USER_B },
      false,
    ],
    [
      'employee writes own campaign',
      employeeSession,
      'write',
      'campaign',
      { ownerId: USER_A },
      true,
    ],
    [
      'employee writes own social post',
      employeeSession,
      'write',
      'socialPost',
      { ownerId: USER_A },
      true,
    ],
    [
      'employee writes own dev task',
      employeeSession,
      'write',
      'devTask',
      { ownerId: USER_A },
      true,
    ],
    [
      "employee cannot write someone else's dev task",
      employeeSession,
      'write',
      'devTask',
      { ownerId: USER_B, createdById: USER_B },
      false,
    ],

    // EMPLOYEE — create-new path (no record argument)
    ['employee creates a new lead', employeeSession, 'write', 'lead', undefined, true],
    ['employee creates a new campaign', employeeSession, 'write', 'campaign', undefined, true],
    [
      'employee creates a new social post',
      employeeSession,
      'write',
      'socialPost',
      undefined,
      true,
    ],
    ['employee creates a new dev task', employeeSession, 'write', 'devTask', undefined, true],

    // EMPLOYEE — delete is always denied (SPEC: admin-only across modules)
    [
      'employee cannot delete own lead',
      employeeSession,
      'delete',
      'lead',
      { ownerId: USER_A },
      false,
    ],
    [
      'employee cannot delete own campaign',
      employeeSession,
      'delete',
      'campaign',
      { ownerId: USER_A },
      false,
    ],
    [
      'employee cannot delete own dev task',
      employeeSession,
      'delete',
      'devTask',
      { ownerId: USER_A },
      false,
    ],

    // Unauthenticated
    ['null session denies read', null, 'read', 'lead', undefined, false],
    ['null session denies write', null, 'write', 'lead', { ownerId: USER_A }, false],
    ['null session denies delete', null, 'delete', 'lead', undefined, false],
    ['undefined session denies admin', undefined, 'admin', 'aiInsight', undefined, false],
  ];

  it.each(rows)('%s', (_label, session, action, resource, record, expected) => {
    expect(can(session, action, resource, record)).toBe(expected);
  });
});

// ---------------------------------------------------------------------------
// RESOURCE_ACTIONS sanity (cartesian product covers everything once)
// ---------------------------------------------------------------------------

describe('RESOURCE_ACTIONS cartesian product', () => {
  it('covers every (resource, action) exactly once', () => {
    expect(RESOURCE_ACTIONS).toHaveLength(RESOURCES.length * ACTIONS.length);
    const seen = new Set<string>();
    for (const { resource, action } of RESOURCE_ACTIONS) {
      const key = `${resource}:${action}`;
      expect(seen.has(key)).toBe(false);
      seen.add(key);
    }
    expect(seen.size).toBe(RESOURCES.length * ACTIONS.length);
  });

  it('admin can do every (resource, action) in the cartesian product', () => {
    for (const { resource, action } of RESOURCE_ACTIONS) {
      expect(can(adminSession, action, resource)).toBe(true);
    }
  });
});

// ---------------------------------------------------------------------------
// assertCan() / PermissionError
// ---------------------------------------------------------------------------

describe('assertCan()', () => {
  it('does not throw when can() returns true', () => {
    expect(() => assertCan(adminSession, 'delete', 'user')).not.toThrow();
    expect(() => assertCan(employeeSession, 'read', 'lead')).not.toThrow();
    expect(() =>
      assertCan(employeeSession, 'write', 'lead', { ownerId: USER_A }),
    ).not.toThrow();
  });

  it('throws PermissionError when can() returns false', () => {
    expect(() => assertCan(employeeSession, 'delete', 'lead')).toThrow(PermissionError);
    expect(() => assertCan(null, 'read', 'lead')).toThrow(PermissionError);
  });

  it('PermissionError carries action, resource, and forbidden code', () => {
    try {
      assertCan(employeeSession, 'admin', 'aiInsight');
      throw new Error('should have thrown');
    } catch (err) {
      expect(err).toBeInstanceOf(PermissionError);
      const perr = err as PermissionError;
      expect(perr.code).toBe('forbidden');
      expect(perr.action).toBe('admin');
      expect(perr.resource).toBe('aiInsight');
      expect(perr.message).toContain('admin');
      expect(perr.message).toContain('aiInsight');
      expect(perr.name).toBe('PermissionError');
    }
  });

  it('uses a custom message when provided', () => {
    const err = new PermissionError('write', 'lead', 'custom msg');
    expect(err.message).toBe('custom msg');
  });
});

// ---------------------------------------------------------------------------
// Defensive: unknown roles are denied (forward-compatibility)
// ---------------------------------------------------------------------------

describe('Defensive — unknown role is denied', () => {
  it('returns false for any role string the system does not recognise', () => {
    fc.assert(
      fc.property(actionArb, resourceArb, (action, resource) => {
        const weirdSession = { userId: USER_A, role: 'GHOST' as unknown as 'ADMIN' };
        expect(can(weirdSession, action, resource)).toBe(false);
      }),
      { numRuns: 50 },
    );
  });
});

// ---------------------------------------------------------------------------
// canAccessModule() — per-module whitelist gating
// ---------------------------------------------------------------------------

const moduleIdArb = fc.constantFrom(...ALL_EMPLOYEE_MODULES) as fc.Arbitrary<ModuleId>;

/** Arbitrary subset of the module list, possibly empty. */
const moduleAccessArb: fc.Arbitrary<ModuleId[]> = fc.subarray(
  ALL_EMPLOYEE_MODULES as unknown as ModuleId[],
);

describe('canAccessModule() — admin bypass', () => {
  it('returns true for every module regardless of moduleAccess', () => {
    fc.assert(
      fc.property(moduleIdArb, moduleAccessArb, (moduleId, moduleAccess) => {
        expect(
          canAccessModule({ role: 'ADMIN', moduleAccess }, moduleId),
        ).toBe(true);
      }),
      { numRuns: 200 },
    );
  });

  it('admin with null moduleAccess still has full access', () => {
    for (const moduleId of ALL_EMPLOYEE_MODULES) {
      expect(canAccessModule({ role: 'ADMIN', moduleAccess: null }, moduleId)).toBe(true);
    }
  });

  it('admin with undefined moduleAccess still has full access', () => {
    for (const moduleId of ALL_EMPLOYEE_MODULES) {
      expect(canAccessModule({ role: 'ADMIN' }, moduleId)).toBe(true);
    }
  });
});

describe('canAccessModule() — employee legacy semantics (empty list = full access)', () => {
  it('employee with empty moduleAccess can access every module', () => {
    fc.assert(
      fc.property(moduleIdArb, (moduleId) => {
        expect(
          canAccessModule({ role: 'EMPLOYEE', moduleAccess: [] }, moduleId),
        ).toBe(true);
      }),
      { numRuns: 50 },
    );
  });

  it('employee with null moduleAccess can access every module (DB default)', () => {
    for (const moduleId of ALL_EMPLOYEE_MODULES) {
      expect(
        canAccessModule({ role: 'EMPLOYEE', moduleAccess: null }, moduleId),
      ).toBe(true);
    }
  });

  it('employee with undefined moduleAccess can access every module', () => {
    for (const moduleId of ALL_EMPLOYEE_MODULES) {
      expect(canAccessModule({ role: 'EMPLOYEE' }, moduleId)).toBe(true);
    }
  });
});

describe('canAccessModule() — employee explicit whitelist', () => {
  it("employee with ['leads'] can access leads but not marketing", () => {
    const user = { role: 'EMPLOYEE' as const, moduleAccess: ['leads'] };
    expect(canAccessModule(user, 'leads')).toBe(true);
    expect(canAccessModule(user, 'marketing')).toBe(false);
    expect(canAccessModule(user, 'dashboard')).toBe(false);
    expect(canAccessModule(user, 'employees')).toBe(false);
    expect(canAccessModule(user, 'social')).toBe(false);
    expect(canAccessModule(user, 'dev')).toBe(false);
  });

  it('employee with all 6 modules can access every module', () => {
    const user = {
      role: 'EMPLOYEE' as const,
      moduleAccess: [...ALL_EMPLOYEE_MODULES],
    };
    for (const moduleId of ALL_EMPLOYEE_MODULES) {
      expect(canAccessModule(user, moduleId)).toBe(true);
    }
  });

  it('once any module is set, the list is the exhaustive whitelist', () => {
    // Single-module case: only that one module is accessible.
    fc.assert(
      fc.property(moduleIdArb, moduleIdArb, (granted, candidate) => {
        const user = { role: 'EMPLOYEE' as const, moduleAccess: [granted] };
        expect(canAccessModule(user, candidate)).toBe(granted === candidate);
      }),
      { numRuns: 100 },
    );
  });

  it('membership matches exactly the whitelist', () => {
    fc.assert(
      fc.property(moduleAccessArb, moduleIdArb, (whitelist, candidate) => {
        fc.pre(whitelist.length > 0);
        const user = { role: 'EMPLOYEE' as const, moduleAccess: whitelist };
        expect(canAccessModule(user, candidate)).toBe(whitelist.includes(candidate));
      }),
      { numRuns: 200 },
    );
  });
});

describe('canAccessModule() — unauthenticated', () => {
  it('null user denies every module', () => {
    for (const moduleId of ALL_EMPLOYEE_MODULES) {
      expect(canAccessModule(null, moduleId)).toBe(false);
    }
  });

  it('undefined user denies every module', () => {
    for (const moduleId of ALL_EMPLOYEE_MODULES) {
      expect(canAccessModule(undefined, moduleId)).toBe(false);
    }
  });
});

describe('canAccessModule() — runtime safety for unknown moduleId casts', () => {
  // TypeScript prevents passing arbitrary strings as `moduleId`, but a
  // caller can always force a cast (`'bogus' as ModuleId`). The runtime
  // behaviour must still be sensible: unknown ids are simply not in the
  // whitelist, so they're denied for employees with an explicit list and
  // allowed for the legacy / admin paths (bypass occurs before lookup).
  it('unknown moduleId is denied for employee with explicit whitelist', () => {
    const user = { role: 'EMPLOYEE' as const, moduleAccess: ['leads'] };
    expect(canAccessModule(user, 'bogus' as ModuleId)).toBe(false);
  });

  it('unknown moduleId is allowed for employee with empty whitelist (legacy)', () => {
    const user = { role: 'EMPLOYEE' as const, moduleAccess: [] };
    expect(canAccessModule(user, 'bogus' as ModuleId)).toBe(true);
  });

  it('unknown moduleId is allowed for ADMIN (bypass short-circuits)', () => {
    const user = { role: 'ADMIN' as const, moduleAccess: ['leads'] };
    expect(canAccessModule(user, 'bogus' as ModuleId)).toBe(true);
  });
});
